services:
  - type: web
    name: webhook-stripe-handler
    env: node
    plan: free
    buildCommand: npm install
    startCommand: NODE_OPTIONS=--openssl-legacy-provider node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
      - key: STRIPE_SECRET_KEY_LIVE
        sync: false
      - key: STRIPE_SECRET_KEY_TEST
        sync: false
      - key: STRIPE_WEBHOOK_SECRET_LIVE
        sync: false
      - key: STRIPE_WEBHOOK_SECRET_TEST
        sync: false
      - key: SPREADSHEET_ID
        value: 1EDW7_34dnjCHBtqd4jXrYgOB8HovgPdXcuod1k3_i4A
    autoDeploy: true
